# Medium Model Variant Configuration
# =================================
# Balanced model for good performance vs. speed

model:
  hidden_size: 512
  num_hidden_layers: 8
  num_attention_heads: 8
  intermediate_size: 2048

# Standard training settings
data:
  batch_size: 24
