# Small Model Variant Configuration
# ================================
# Smaller model for quick experimentation and testing

model:
  hidden_size: 256
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1024

# Reduced training settings for faster iterations
trainer:
  max_epochs: 50

# Smaller batch size for memory efficiency
data:
  batch_size: 16
