name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black isort pytest pytest-cov
        pip install -e .

    - name: Run MyPy (allow failure)
      run: mypy --config-file mypy.ini . || echo "MyPy found issues, but continuing..."
      continue-on-error: true

    - name: Check Black formatting (allow failure)
      run: black . --check --exclude "(.git|__pycache__|.pytest_cache|experiments|polydiff.egg-info|notebook)" || echo "Black formatting issues found, but continuing..."
      continue-on-error: true

    - name: Check isort sorting (allow failure)
      run: isort . --check-only --skip-glob "__pycache__,.pytest_cache,experiments,polydiff.egg-info,notebook" || echo "Import sorting issues found, but continuing..."
      continue-on-error: true

    - name: Run tests and collect coverage
      run: pytest --cov=polydiff --cov-report=xml || echo "Some tests failed, but continuing..."
      continue-on-error: true

    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
      continue-on-error: true