name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black isort pytest pytest-cov
        pip install -e .

    - name: Run MyPy
      run: mypy --config-file mypy.ini .

    - name: Check Black formatting
      run: black . --check --exclude "(.git|__pycache__|.pytest_cache|experiments|polydiff.egg-info|notebook)"

    - name: Check isort sorting
      run: isort . --check-only --skip-glob "__pycache__,.pytest_cache,experiments,polydiff.egg-info,notebook"

    - name: Run tests and collect coverage
      run: pytest --cov=polydiff --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true